package Gates

import chisel3._
import chisel3.tester._
import org.scalatest.FreeSpec
import chisel3.experimental.BundleLiterals._


class Thirtytwobitfulladdertest extends FreeSpec with ChiselScalatestTester {
  "dut test" in {
    test(new Thirtytwobitfulladder) { dut =>



   dut.io.a1.poke(0.B)
   dut.io.b1.poke(0.B)
   dut.io.a2.poke(0.B)
   dut.io.b2.poke(0.B)
   dut.io.a3.poke(0.B)
   dut.io.b3.poke(0.B)
   dut.io.a4.poke(0.B)
   dut.io.b4.poke(0.B)
   dut.io.a5.poke(0.B)
   dut.io.b5.poke(0.B)
   dut.io.a6.poke(0.B)
   dut.io.b6.poke(0.B)
   dut.io.a7.poke(0.B)
   dut.io.b7.poke(0.B)
   dut.io.a8.poke(0.B)
   dut.io.b8.poke(0.B)
   dut.io.a9.poke(0.B)
   dut.io.b9.poke(0.B)
   dut.io.a10.poke(0.B)
   dut.io.b10.poke(0.B)
   dut.io.a11.poke(0.B)
   dut.io.b11.poke(0.B)
   dut.io.a12.poke(0.B)
   dut.io.b12.poke(0.B)
   dut.io.a13.poke(0.B)
   dut.io.b13.poke(0.B)
   dut.io.a14.poke(0.B)
   dut.io.b14.poke(0.B)
   dut.io.a15.poke(0.B)
   dut.io.b15.poke(0.B)
   dut.io.a16.poke(0.B)
   dut.io.b16.poke(0.B)
   dut.io.a17.poke(0.B)
   dut.io.b17.poke(0.B)
   dut.io.a18.poke(0.B)
   dut.io.b18.poke(0.B)
   dut.io.a19.poke(0.B)
   dut.io.b19.poke(0.B)
   dut.io.a20.poke(0.B)
   dut.io.b20.poke(0.B)
   dut.io.a21.poke(0.B)
   dut.io.b21.poke(0.B)
   dut.io.a22.poke(0.B)
   dut.io.b22.poke(0.B)
   dut.io.a23.poke(0.B)
   dut.io.b23.poke(0.B)
   dut.io.a24.poke(0.B)
   dut.io.b24.poke(0.B)
   dut.io.a25.poke(0.B)
   dut.io.b25.poke(0.B)
   dut.io.a26.poke(0.B)
   dut.io.b26.poke(0.B)
   dut.io.a27.poke(0.B)
   dut.io.b27.poke(0.B)
   dut.io.a28.poke(0.B)
   dut.io.b28.poke(0.B)
   dut.io.a29.poke(0.B)
   dut.io.b29.poke(0.B)
   dut.io.a30.poke(0.B)
   dut.io.b30.poke(0.B)
   dut.io.a31.poke(0.B)
   dut.io.b31.poke(0.B)
   dut.io.a32.poke(0.B)
   dut.io.b32.poke(0.B)


   dut.io.sum1.expect(0.B)  
   dut.io.sum2.expect(0.B)  
   dut.io.sum3.expect(0.B)  
   dut.io.sum4.expect(0.B)  
   dut.io.sum5.expect(0.B)  
   dut.io.sum6.expect(0.B)  
   dut.io.sum7.expect(0.B)  
   dut.io.sum8.expect(0.B)
   dut.io.sum9.expect(0.B)
   dut.io.sum10.expect(0.B)
   dut.io.sum11.expect(0.B)
   dut.io.sum12.expect(0.B)
   dut.io.sum13.expect(0.B)
   dut.io.sum14.expect(0.B)
   dut.io.sum15.expect(0.B)
   dut.io.sum16.expect(0.B)
   dut.io.sum17.expect(0.B)
   dut.io.sum18.expect(0.B)
   dut.io.sum19.expect(0.B)
   dut.io.sum20.expect(0.B)
   dut.io.sum21.expect(0.B)
   dut.io.sum22.expect(0.B)
   dut.io.sum23.expect(0.B)
   dut.io.sum24.expect(0.B)
   dut.io.sum25.expect(0.B)
   dut.io.sum26.expect(0.B)
   dut.io.sum27.expect(0.B)
   dut.io.sum28.expect(0.B)
   dut.io.sum29.expect(0.B)
   dut.io.sum30.expect(0.B)
   dut.io.sum31.expect(0.B)
   dut.io.sum32.expect(0.B)

   dut.io.cout.expect(0.B)  

   dut.clock.step(1)
   
    }
  }
}
