package Gates
import chisel3._
import javax.swing.UIManager.LookAndFeelInfo


class Thirtytwobitfulladder extends Module {
    val io = IO(new Bundle{

            val a1 = Input(Bool())
            val a2 = Input(Bool())
            val a3 = Input(Bool())
            val a4 = Input(Bool())
            val a5 = Input(Bool())
            val a6 = Input(Bool())
            val a7 = Input(Bool())
            val a8 = Input(Bool())
            val a9 = Input(Bool())
            val a10 = Input(Bool())
            val a11 = Input(Bool())
            val a12 = Input(Bool())
            val a13 = Input(Bool())
            val a14 = Input(Bool())
            val a15 = Input(Bool())
            val a16 = Input(Bool())
            val a17 = Input(Bool())
            val a18 = Input(Bool())
            val a19 = Input(Bool())
            val a20 = Input(Bool())
            val a21 = Input(Bool())
            val a22 = Input(Bool())
            val a23 = Input(Bool())
            val a24 = Input(Bool())
            val a25 = Input(Bool())
            val a26 = Input(Bool())
            val a27 = Input(Bool())
            val a28 = Input(Bool())
            val a29 = Input(Bool())
            val a30 = Input(Bool())
            val a31 = Input(Bool())
            val a32 = Input(Bool())
            
            val b1 = Input(Bool())
            val b2 = Input(Bool())
            val b3 = Input(Bool())
            val b4 = Input(Bool())
            val b5 = Input(Bool())
            val b6 = Input(Bool())
            val b7 = Input(Bool())
            val b8 = Input(Bool())
            val b9 = Input(Bool())
            val b10 = Input(Bool())
            val b11 = Input(Bool())
            val b12 = Input(Bool())
            val b13 = Input(Bool())
            val b14 = Input(Bool())
            val b15 = Input(Bool())
            val b16 = Input(Bool())
            val b17 = Input(Bool())
            val b18 = Input(Bool())
            val b19 = Input(Bool())
            val b20 = Input(Bool())
            val b21 = Input(Bool())
            val b22 = Input(Bool())
            val b23 = Input(Bool())
            val b24 = Input(Bool())
            val b25 = Input(Bool())
            val b26 = Input(Bool())
            val b27 = Input(Bool())
            val b28 = Input(Bool())
            val b29 = Input(Bool())
            val b30 = Input(Bool())
            val b31 = Input(Bool())
            val b32 = Input(Bool())

           val sum1 = Output(Bool())
           val sum2 = Output(Bool())
           val sum3 = Output(Bool())
           val sum4 = Output(Bool())
           val sum5 = Output(Bool())
           val sum6 = Output(Bool())
           val sum7 = Output(Bool())
           val sum8 = Output(Bool())
           val sum9 = Output(Bool())
           val sum10 = Output(Bool())
           val sum11 = Output(Bool())
           val sum12 = Output(Bool())
           val sum13 = Output(Bool())
           val sum14 = Output(Bool())
           val sum15 = Output(Bool())
           val sum16 = Output(Bool())
           val sum17 = Output(Bool())
           val sum18 = Output(Bool())
           val sum19 = Output(Bool())
           val sum20 = Output(Bool())
           val sum21 = Output(Bool())
           val sum22 = Output(Bool())
           val sum23 = Output(Bool())
           val sum24 = Output(Bool())
           val sum25 = Output(Bool())
           val sum26 = Output(Bool())
           val sum27 = Output(Bool())
           val sum28 = Output(Bool())
           val sum29 = Output(Bool())
           val sum30 = Output(Bool())
           val sum31 = Output(Bool())
           val sum32 = Output(Bool())

           val cout = Output(Bool())
    })
    
    val halfadder = Module(new Half_Adder)
    val fulladder1 = Module(new Full_Adder)
    val fulladder2 = Module(new Full_Adder)
    val fulladder3 = Module(new Full_Adder)
    val fulladder4 = Module(new Full_Adder)
    val fulladder5 = Module(new Full_Adder)
    val fulladder6 = Module(new Full_Adder)
    val fulladder7 = Module(new Full_Adder)
    val fulladder8 = Module(new Full_Adder)
    val fulladder9 = Module(new Full_Adder)
    val fulladder10 = Module(new Full_Adder)
    val fulladder11 = Module(new Full_Adder)
    val fulladder12 = Module(new Full_Adder)
    val fulladder13 = Module(new Full_Adder)
    val fulladder14 = Module(new Full_Adder)
    val fulladder15 = Module(new Full_Adder)
    val fulladder16 = Module(new Full_Adder)
    val fulladder17 = Module(new Full_Adder)
    val fulladder18 = Module(new Full_Adder)
    val fulladder19 = Module(new Full_Adder)
    val fulladder20 = Module(new Full_Adder)
    val fulladder21 = Module(new Full_Adder)
    val fulladder22 = Module(new Full_Adder)
    val fulladder23 = Module(new Full_Adder)
    val fulladder24 = Module(new Full_Adder)
    val fulladder25 = Module(new Full_Adder)
    val fulladder26 = Module(new Full_Adder)
    val fulladder27 = Module(new Full_Adder)
    val fulladder28 = Module(new Full_Adder)
    val fulladder29 = Module(new Full_Adder)
    val fulladder30 = Module(new Full_Adder)
    val fulladder31 = Module(new Full_Adder)

    fulladder1.io.c := halfadder.io.carry_output
    fulladder2.io.c := fulladder1.io.cout
    fulladder3.io.c := fulladder2.io.cout
    fulladder4.io.c := fulladder3.io.cout
    fulladder5.io.c := fulladder4.io.cout
    fulladder6.io.c := fulladder5.io.cout
    fulladder7.io.c := fulladder6.io.cout
    fulladder8.io.c := fulladder7.io.cout
    fulladder9.io.c := fulladder8.io.cout
    fulladder10.io.c := fulladder9.io.cout
    fulladder11.io.c := fulladder10.io.cout
    fulladder12.io.c := fulladder11.io.cout
    fulladder13.io.c := fulladder12.io.cout
    fulladder14.io.c := fulladder13.io.cout
    fulladder15.io.c := fulladder14.io.cout
    fulladder16.io.c := fulladder15.io.cout
    fulladder17.io.c := fulladder16.io.cout
    fulladder18.io.c := fulladder17.io.cout
    fulladder19.io.c := fulladder18.io.cout
    fulladder20.io.c := fulladder19.io.cout
    fulladder21.io.c := fulladder20.io.cout
    fulladder22.io.c := fulladder21.io.cout
    fulladder23.io.c := fulladder22.io.cout
    fulladder24.io.c := fulladder23.io.cout
    fulladder25.io.c := fulladder24.io.cout
    fulladder26.io.c := fulladder25.io.cout
    fulladder27.io.c := fulladder26.io.cout
    fulladder28.io.c := fulladder27.io.cout
    fulladder29.io.c := fulladder28.io.cout
    fulladder30.io.c := fulladder29.io.cout
    fulladder31.io.c := fulladder30.io.cout

    halfadder.io.a := io.a1
    halfadder.io.b := io.b1

    fulladder1.io.a := io.a2
    fulladder1.io.b := io.b2
    fulladder2.io.a := io.a3
    fulladder2.io.b := io.b3
    fulladder3.io.a := io.a4
    fulladder3.io.b := io.b4
    fulladder4.io.a := io.a5
    fulladder4.io.b := io.b5
    fulladder5.io.a := io.a6
    fulladder5.io.b := io.b6
    fulladder6.io.a := io.a7
    fulladder6.io.b := io.b7
    fulladder7.io.a := io.a8
    fulladder7.io.b := io.b8
    fulladder8.io.a := io.a9
    fulladder8.io.b := io.b9
    fulladder9.io.a := io.a10
    fulladder9.io.b := io.b10
    fulladder10.io.a := io.a11
    fulladder10.io.b := io.b11
    fulladder11.io.a := io.a12
    fulladder11.io.b := io.b12
    fulladder12.io.a := io.a13
    fulladder12.io.b := io.b13
    fulladder13.io.a := io.a14
    fulladder13.io.b := io.b14
    fulladder14.io.a := io.a15
    fulladder14.io.b := io.b15
    fulladder15.io.a := io.a16
    fulladder15.io.b := io.b16
    fulladder16.io.a := io.a17
    fulladder16.io.b := io.b17
    fulladder17.io.a := io.a18
    fulladder17.io.b := io.b18
    fulladder18.io.a := io.a19
    fulladder18.io.b := io.b19
    fulladder19.io.a := io.a20
    fulladder19.io.b := io.b20
    fulladder20.io.a := io.a21
    fulladder20.io.b := io.b21
    fulladder21.io.a := io.a22
    fulladder21.io.b := io.b22
    fulladder22.io.a := io.a23
    fulladder22.io.b := io.b23
    fulladder23.io.a := io.a24
    fulladder23.io.b := io.b24
    fulladder24.io.a := io.a25
    fulladder24.io.b := io.b25
    fulladder25.io.a := io.a26
    fulladder25.io.b := io.b26
    fulladder26.io.a := io.a27
    fulladder26.io.b := io.b27
    fulladder27.io.a := io.a28
    fulladder27.io.b := io.b28
    fulladder28.io.a := io.a29
    fulladder28.io.b := io.b29
    fulladder29.io.a := io.a30
    fulladder29.io.b := io.b30
    fulladder30.io.a := io.a31
    fulladder30.io.b := io.b31
    fulladder31.io.a := io.a32
    fulladder31.io.b := io.b32

    io.sum1 := halfadder.io.sum_output
    io.sum2 := fulladder1.io.sum
    io.sum3 := fulladder2.io.sum
    io.sum4 := fulladder3.io.sum
    io.sum5 := fulladder4.io.sum
    io.sum6 := fulladder5.io.sum
    io.sum7 := fulladder6.io.sum
    io.sum8 := fulladder7.io.sum
    io.sum9 := fulladder8.io.sum
    io.sum10 := fulladder9.io.sum
    io.sum11 := fulladder10.io.sum
    io.sum12 := fulladder11.io.sum
    io.sum13 := fulladder12.io.sum
    io.sum14 := fulladder13.io.sum
    io.sum15 := fulladder14.io.sum
    io.sum16 := fulladder15.io.sum
    io.sum17 := fulladder16.io.sum
    io.sum18 := fulladder17.io.sum
    io.sum19 := fulladder18.io.sum
    io.sum20 := fulladder19.io.sum
    io.sum21 := fulladder20.io.sum
    io.sum22 := fulladder21.io.sum
    io.sum23 := fulladder22.io.sum
    io.sum24 := fulladder23.io.sum
    io.sum25 := fulladder24.io.sum
    io.sum26 := fulladder25.io.sum
    io.sum27 := fulladder26.io.sum
    io.sum28 := fulladder27.io.sum
    io.sum29 := fulladder28.io.sum
    io.sum30 := fulladder29.io.sum
    io.sum31 := fulladder30.io.sum
    io.sum32 := fulladder31.io.sum
    
    io.cout := fulladder31.io.cout
}
